//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tydee.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collection
    {
        public Collection()
        {
            this.Items = new HashSet<Item>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string EBayName { get; set; }
        public string ShopInfo { get; set; }
        public int UserId { get; set; }
    
        public virtual CollectionOption CollectionOption { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Item> Items { get; set; }
    }
}
