//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tydee.DataModels
{
    using System;
    
    public enum ItemDamages : int
    {
        None = 0,
        MinorProblems = 1,
        LowDamage = 2,
        HighDamage = 3
    }
}
