//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tydee.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.Pictures = new HashSet<Picture>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string PublicInfo { get; set; }
        public string PrivateInfo { get; set; }
        public Nullable<decimal> BuyPrice { get; set; }
        public Nullable<decimal> SellPrice { get; set; }
        public bool Owned { get; set; }
        public bool Searched { get; set; }
        public bool Sold { get; set; }
        public bool Exchanged { get; set; }
        public bool Archived { get; set; }
        public bool Salable { get; set; }
        public bool Favorite { get; set; }
        public ItemConditions Conditions { get; set; }
        public ItemDamages Damage { get; set; }
    
        public virtual Collection Collection { get; set; }
        public virtual ICollection<Picture> Pictures { get; set; }
    }
}
