//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tydee.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop
    {
        public int Id { get; set; }
        public bool Enabled { get; set; }
        public string PaymentInfo { get; set; }
        public string ShipmentInfo { get; set; }
        public bool ShowOwned { get; set; }
        public bool ShowSearched { get; set; }
        public bool ShowSalable { get; set; }
    
        public virtual User User { get; set; }
    }
}
