//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tydee.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Collections = new HashSet<Collection>();
            this.Shops = new HashSet<Shop>();
        }
    
        public int Id { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime LastAccessDate { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public bool SocialCreated { get; set; }
        public string ImportId { get; set; }
    
        public virtual UserOption UserOption { get; set; }
        public virtual ICollection<Collection> Collections { get; set; }
        public virtual ICollection<Shop> Shops { get; set; }
    }
}
