//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tydee.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserOption
    {
        public int Id { get; set; }
        public bool ShowPhoto { get; set; }
        public CollectionOrders CollectionOrder { get; set; }
        public bool DialogOnNew { get; set; }
    
        public virtual User User { get; set; }
        public virtual CollectionOption DefaultCollectionOption { get; set; }
    }
}
